# Generated by Django 3.1.7 on 2021-03-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('IND', 'Individual'), ('BUS', 'Business')], default='IND', max_length=3)),
                ('username', models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
