# Generated by Django 3.1.7 on 2021-03-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='msisdn',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(choices=[('IND', 'Individual'), ('BUS', 'Business')], default='IND', max_length=3),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
