# Generated by Django 3.1.7 on 2021-03-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='msisdn',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
