# Generated by Django 3.1.7 on 2021-03-16 00:14

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20210303_0000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customer',
            managers=[
                ('business', django.db.models.manager.Manager()),
            ],
        ),
    ]
