# Generated by Django 3.1.7 on 2021-03-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_auto_20210303_0000'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortMessageService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('send_date', models.DateTimeField()),
                ('sending_party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smses_sent', to='customers.customer')),
                ('sent_party_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smses_received', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_received', to='customers.customer')),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls_made', to='customers.customer')),
            ],
        ),
    ]
