# Generated by Django 3.1.7 on 2021-03-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortmessageservice',
            old_name='sending_party_id',
            new_name='sending_party',
        ),
        migrations.RenameField(
            model_name='shortmessageservice',
            old_name='sent_party_id',
            new_name='sent_party',
        ),
    ]
