# Generated by Django 3.1.7 on 2021-03-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='callee',
        ),
        migrations.RemoveField(
            model_name='call',
            name='caller',
        ),
        migrations.RemoveField(
            model_name='shortmessageservice',
            name='sending_party_id',
        ),
        migrations.RemoveField(
            model_name='shortmessageservice',
            name='sent_party_id',
        ),
    ]
